=== yanka93/CRADLEOFTEARS/ljcom/doc/raw/local/hardware.dtd
<!ELEMENT hardwarelist (machine*)>

<!ELEMENT machine (physical, config, notes?)>
  <!ATTLIST machine name ID #REQUIRED>

<!ELEMENT physical (type, vendor?, size?, proc?, mem?, disk?, other*)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT vendor (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT proc (#PCDATA)>
<!ELEMENT mem (#PCDATA)>
<!ELEMENT disk (#PCDATA)>
<!ELEMENT other (#PCDATA)>
  <!ATTLIST other count NMTOKEN '1'>

<!ELEMENT config (role*, os?, raid*, ip*, mysqlid?)>
<!ELEMENT role (#PCDATA)>
<!ELEMENT os (#PCDATA)>
<!ELEMENT raid (#PCDATA)>
  <!ATTLIST raid config NMTOKEN #REQUIRED>
<!ELEMENT ip (#PCDATA)>
<!ELEMENT mysqlid (#PCDATA)>

<!ELEMENT notes (#PCDATA)>

=== yanka93/CRADLEOFTEARS/ljcom/doc/raw/local/hardware.xml
<?xml version="1.0"?>
<!DOCTYPE hardwarelist SYSTEM "hardware.dtd">
<hardwarelist>

<machine name="kenny">
<physical>
  <type>server</type>
  <vendor>Dell</vendor>
  <size>6</size>
  <proc>Dual P3 (Coppermine) 933 Mhz</proc>
  <mem>2 GB</mem>
  <disk>SCSI: 2x9 GB, 2x18 GB</disk>
  <other>AMI MegaRAID card</other>
  <other count='2'>eepro100</other>
</physical>
<config>
  <role>db</role>
  <os>Debian</os>
  <raid config='1'>9 GB</raid>
  <raid config='0'>36 GB</raid>
  <ip>10.0.0.1</ip>
  <mysqlid>2</mysqlid>
</config>
<notes>
Kenny was one of our first two servers.  We bought it at the
same time as Cartman.  Kenny was our web server and 
named so we could say "You killed Kenny, you bastard!" since
we anticipated growth faster than we could buy new servers.
</notes>
</machine>

<machine name="cartman">
<physical>
  <type>server</type>
  <vendor>Dell</vendor>
  <size>6</size>
  <proc>Dual P3 (Coppermine) 866 Mhz</proc>
  <mem>2 GB</mem>
  <disk>SCSI: 2x9 GB, 2x18 GB, 2x18 GB 10k</disk>
  <other>AMI MegaRAID card</other>
  <other count='2'>eepro100</other>
</physical>
<config>
  <role>cluster master</role>
  <os>Debian</os>
  <raid config='1'>9 GB</raid>
  <raid config='5'>36 GB (1 hotspare)</raid>
  <ip>10.0.0.2</ip>
  <mysqlid>1</mysqlid>
</config>
<notes>
Cartman was one of our first two servers along with Kenny.
Cartman's a big fat ass, and so was this thing, both in
physical size and disk space.  It was our master database
server until we got Jesus and Kyle's mom.  Now it's a
cluster master.
</notes>
</machine>

<machine name="stan">
<physical>
  <type>server</type>
  <vendor>ASL</vendor>
  <size>1</size>
  <proc>Dual P3 (Coppermine) 800 Mhz</proc>
  <mem>512 MB</mem>
  <disk>IDE: 18 GB</disk>
  <other count='2'>eepro100</other>
</physical>
<config>
  <role>web</role>
  <os>Debian</os>
  <ip>10.0.0.3</ip>
</config>
<notes>
Stan and Kyle were bought at the same time.  No front panel.
hda serial: IBM-DTLA-307020 - Model: IBM 75GXP 20.57GB
</notes>
</machine>

<machine name="kyle">
<physical>
  <type>server</type>
  <vendor>ASL</vendor>
  <size>1</size>
  <proc>Dual P3 (Coppermine) 800 Mhz</proc>
  <mem>512 MB</mem>
  <disk>IDE: 18 GB</disk>
  <other count='2'>eepro100</other>
</physical>
<config>
  <role>web</role>
  <role>mail backup</role>
  <os>FreeBSD</os>
  <ip>10.0.0.4</ip>
</config>
<notes>
Stan and Kyle were bought at the same time.  No front panel.
hda serial: IBM-DTLA-307020 - Model: IBM 75GXP 20.57GB
</notes>
</machine>

<machine name="wendy">
<physical>
  <type>server</type>
  <vendor>ASL</vendor>
  <size>1</size>
  <proc>Dual P3 (Coppermine) 800 Mhz</proc>
  <mem>512 MB</mem>
  <disk>IDE: 18 GB</disk>
  <other count='2'>eepro100</other>
</physical>
<config>
  <role>web</role>
  <os>Debian</os>
  <ip>10.0.0.5</ip>
</config>
<notes>
Bought with Bebe.  Named as such because we have a 60% female user base and had no female servers.
</notes>
</machine>

<machine name="bebe">
<physical>
  <type>server</type>
  <vendor>ASL</vendor>
  <size>1</size>
  <proc>Dual P3 (Coppermine) 800 Mhz</proc>
  <mem>512 MB</mem>
  <disk>IDE: 18 GB</disk>
  <other count='2'>eepro100</other>
</physical>
<config>
  <role>mail</role>
  <role>userpic</role>
  <os>Debian</os>
  <ip>10.0.0.6</ip>
</config>
<notes>
Bought with Wendy.  They're best friends.
hda serial: IBM-DTLA-307020 - Model: IBM 75GXP 20.57GB
</notes>
</machine>

<machine name="terrance">
<physical>
  <type>server</type>
  <vendor>ASL</vendor>
  <size>1</size>
  <proc>Dual P3 (Coppermine) 866 Mhz</proc>
  <mem>512 MB</mem>
  <disk>IDE: 18 GB</disk>
  <other count='2'>eepro100</other>
</physical>
<config>
  <role>web</role>
  <os>FreeBSD</os>
  <ip>10.0.0.7</ip>
</config>
<notes>
Bought with Phillip.
hda serial: IC35L020AVER07-0 - Model: IBM 60GXP 20.57GB
</notes>
</machine>

<machine name="phillip">
<physical>
  <type>server</type>
  <vendor>ASL</vendor>
  <size>1</size>
  <proc>Dual P3 (Coppermine) 866 Mhz</proc>
  <mem>512 MB</mem>
  <disk>IDE: 18 GB</disk>
  <other count='2'>eepro100</other>
</physical>
<config>
  <role>web</role>
  <os>Debian</os>
  <ip>10.0.0.8</ip>
</config>
<notes>
Bought with Terrance.
hda serial: IC35L020AVER07-0 - Model: IBM 60GXP 20.57GB
</notes>
</machine>

<machine name="mackey">
<physical>
  <type>server</type>
  <vendor>ASL</vendor>
  <size>1</size>
  <proc>Dual P3 (Coppermine) 1 Ghz</proc>
  <mem>3.5 GB</mem>
  <disk>SCSI: 3x18 GB (IBM: DDYS-T18350M)</disk>
  <other>64 MB Mylex AcceleRAID 170 PCI RAID Controller</other>
  <other count='2'>eepro100</other>
</physical>
<config>
  <role>db</role>
  <role>dns</role>
  <os>Debian</os>
  <raid config='5'>36 GB</raid>
  <ip>10.0.0.9</ip>
  <mysqlid>4</mysqlid>
</config>
<notes>
Mackey and Hat (Mr. Mackey and Mr. Hat) were our first 1U db slaves.
</notes>
</machine>

<machine name="hat">
<physical>
  <type>server</type>
  <vendor>ASL</vendor>
  <size>1</size>
  <proc>Dual P3 (Coppermine) 1 Ghz</proc>
  <mem>3 GB</mem>
  <disk>SCSI: 3x18 GB (IBM: DDYS-T18350M)</disk>
  <other>64 MB Mylex AcceleRAID 170 PCI RAID Controller</other>
  <other count='2'>eepro100</other>
</physical>
<config>
  <role>db</role>
  <os>Debian</os>
  <raid config='5'>36 GB</raid>
  <ip>10.0.0.10</ip>
  <mysqlid>5</mysqlid>
</config>
<notes>
Mackey and Hat (Mr. Mackey and Mr. Hat) were our first 1U db slaves.
</notes>
</machine>

<machine name="ike">
<physical>
  <type>server</type>
  <vendor>ASL</vendor>
  <size>1</size>
  <proc>Dual P3 (Coppermine) 1Ghz</proc>
  <mem>512 MB</mem>
  <disk>IDE: 18GB</disk>
  <other count='2'>eepro100</other>
</physical>
<config>
  <role>web</role>
  <os>Debian</os>
  <ip>10.0.0.11</ip>
</config>
<notes>
Bought with Pip.
hda serial: IC35L020AVER07-0 - Model: IBM 60GXP 20.57GB
</notes>
</machine>

<machine name="pip">
<physical>
  <type>server</type>
  <vendor>ASL</vendor>
  <size>1</size>
  <proc>Dual P3 (Coppermine) 1Ghz</proc>
  <mem>512 MB</mem>
  <disk>IDE: 18GB</disk>
  <other count='2'>eepro100</other>
</physical>
<config>
  <role>userpic</role>
  <os>Debian</os>
  <ip>10.0.0.12</ip>
</config>
<notes>
Bought with Ike.
hda serial: IC35L020AVER07-0 - Model: IBM 60GXP 20.57GB
</notes>
</machine>

<machine name="timmy">
<physical>
  <type>server</type>
  <vendor>ESS</vendor>
  <size>1</size>
  <proc>Dual P3 (Coppermine) 1 Ghz</proc>
  <mem>2 GB</mem>
  <disk>SCSI: 2x18 GB (IBM)</disk>
  <other>64 MB Mylex AcceleRAID 170 PCI RAID Controller</other>
  <other count='2'>eepro100</other>
</physical>
<config>
  <role>db</role>
  <os>Debian</os>
  <raid config='0'>36G</raid>
  <ip>10.0.0.13</ip>
  <mysqlid>6</mysqlid>
</config>
<notes>
Timmy and Gobbles. They took more than a month to ship, and arrived
in a non-working state, with some broken hardware.

One drive died.  Now only has 2, in a raid 0 config.
</notes>
</machine>

<machine name="marklar">
<physical>
  <type>server</type>
  <vendor>ASL</vendor>
  <size>2</size>
  <proc>Dual P3 (Coppermine) 933 Mhz</proc>
  <mem>3.5 GB</mem>
  <disk>SCSI: 6x18 GB (IBM DDYS-T18350M)</disk>
  <other>Mylex AcceleRAID 352, 64 MB (dac960)</other>
  <other count='2'>eepro100</other>
</physical>
<config>
  <role>misc</role>
  <os>Debian</os>
  <raid config='5'>85G</raid>
  <ip>10.0.0.15</ip>
  <mysqlid>3</mysqlid>
</config>
<notes>
Brad bought this to replace his old machine at Virtualis, and serves many
misc roles: slave database when needed (if another dies), file backup machine,
log processing, etc.
</notes>
</machine>

<machine name="gobbles">
<physical>          
  <type>server</type>
  <vendor>ESS</vendor>
  <size>1</size>
  <proc>Dual P3 (Coppermine) 1 Ghz</proc>
  <mem>3 GB</mem>
  <disk>SCSI: 3x18 GB (IBM)</disk>
  <other>64 MB Mylex AcceleRAID 170 PCI RAID Controller</other>
  <other count='2'>eepro100</other>
</physical>
<config>  
  <role>db</role>
  <os>Debian</os>
  <raid config='0'>54G</raid>
  <ip>10.0.0.16</ip>
  <mysqlid>7</mysqlid>
</config>
<notes>
Timmy and Gobbles. They took more than a month to ship, and arrived
in a non-working state, with some broken hardware.
</notes>
</machine>

<machine name="mayor">
<physical>
  <type>server</type>
  <vendor>ASL</vendor>
  <size>1</size>
  <proc>P3 (Coppermine) 866 Mhz</proc>
  <mem>256 MB</mem>
  <disk>IDE: 18G</disk>
  <other count='2'>eepro100</other>
</physical>
<config>
  <role>staging</role>
  <role>dns</role>
  <role>netsaint</role>
  <role>statserv</role>
  <os>Debian</os>
  <ip>10.0.0.17</ip>
</config>
<notes>
We bought this machine as an 'el cheapo box to run all of the
monitorying/syncronizing software.
hda serial: IC35L020AVER07-0 - Model: IBM 60GXP 20.57GB
</notes>
</machine>

<machine name="gerald">
<physical>
  <type>server</type>
  <vendor>ASL</vendor>
  <size>1</size>
  <proc>Dual P3 (Tualatin) 1.26 Ghz</proc>
  <mem>512 MB</mem>
  <disk>IDE: 18G</disk>
  <other count='2'>eepro100</other>
</physical>
<config>  
  <role>web</role>
  <os>Debian</os>
  <ip>10.0.0.18</ip>
</config>
<notes> 
Bought with sheila. First ones to go above 1 Ghz, and will
function as the new paid web slaves.
hda serial: IC35L020AVER07-0 - Model: IBM 60GXP 20.57GB
</notes>
</machine>

<machine name="sheila">
<physical>
  <type>server</type>
  <vendor>ASL</vendor>
  <size>1</size>
  <proc>Dual P3 (Tualatin) 1.26 Ghz</proc>
  <mem>512 MB</mem>
  <disk>IDE: 18G</disk>
  <other count='2'>eepro100</other>
</physical>
<config>
  <role>web</role>
  <os>Debian</os>
  <ip>10.0.0.19</ip>
</config>
<notes>
Bought with gerald. First ones to go above 1 Ghz, and will
function as the new paid web slaves.
hda serial: IC35L020AVER07-0 - Model: IBM 60GXP 20.57GB
</notes>
</machine>

<machine name="jesus">
<physical>
  <type>server</type>
  <vendor>ASL</vendor>
  <size>4</size>
  <proc>Dual P3 (Xeon) 700 Mhz (2 MB L2 cache)</proc>
  <mem>12 GB</mem>
  <disk>SCSI: 1x18 GB</disk>
  <other>64 MB IBM ServeRAID-4Mx PCI RAID Controller</other>
  <other>eepro100</other>
</physical>
<config>
  <role>db</role>
  <os>Debian</os>
  <ip>10.0.0.20</ip>
  <mysqlid>8</mysqlid>
</config>
<notes>
